version: '3.2'
services:
  tno-eats:
    container_name: tno-eats
    image: node:16.14
    working_dir: /home/tno-eats
    entrypoint: /entrypoint.sh
    stdin_open: true
    tty: true
    ports:
      - "8545:8545"
      - "8000:8000"
    volumes:
      - ./:/home/tno-eats
      - ./docker/entrypoint.sh:/entrypoint.sh
    networks:
      - shared

networks:
  shared:
    driver: bridge
