version: '3.2'
services:
  truffle:
    container_name: tno_eats
    build:
      context: .
      dockerfile: Dockerfile
    command: ganache -h 0.0.0.0
    stdin_open: true
    tty: true
    ports:
      - "8545:8545"
    volumes:
      - ./:/home/tno-eats
    networks:
      - shared

networks:
  shared:
    driver: bridge
