version: '3.2'
services:
  tom:
    container_name: tom
    image: node:16.14
    working_dir: /home/tom
    entrypoint: /entrypoint.sh
    stdin_open: true
    tty: true
    ports:
      - "8545:8545"
      - "8000:8000"
    volumes:
      - ./:/home/tom
      - ./docker/entrypoint.sh:/entrypoint.sh
    networks:
      - shared

networks:
  shared:
    driver: bridge
