name: Smart Contract Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: NodeJS Setup
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: NodeJS version    
        run: npm --version

      - name: Installing truffle
        run: npm install truffle -g && npm install

      - name: Running Smart Contract Test
        run: CI=true truffle test


